auth_enabled: false

limits_config:
  allow_structured_metadata: true
  volume_enabled: true

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2020-07-01  
    store: tsdb
    object_store: aws
    schema: v13
    index:
      prefix: index_
      period: 24h 

## Role Based 
storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
    cache_ttl: 24h
  aws:
    s3: s3://ap-northeast-2
    bucketnames: donggyu-loki-state

pattern_ingester:
  enabled: true